version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: workout-tracker-db
    environment:
      POSTGRES_DB: workout_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 